INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:15:34] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:15:38] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:15:40] "GET /chain HTTP/1.1" 200 -
ERROR:server:Exception on /mine [GET]
Traceback (most recent call last):
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\xampp\htdocs\basic_blockchain\server.py", line 22, in mine
    blockchain.new_transaction(
TypeError: Blockchain.new_transaction() missing 2 required positional arguments: 'private_key' and 'signature'
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:15:47] "[35m[1mGET /mine?appid={{vault:openweather-api-api-key:value}} HTTP/1.1[0m" 500 -
ERROR:server:Exception on /mine [GET]
Traceback (most recent call last):
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\xampp\htdocs\basic_blockchain\server.py", line 22, in mine
    blockchain.new_transaction(
TypeError: Blockchain.new_transaction() missing 2 required positional arguments: 'private_key' and 'signature'
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:15:49] "[35m[1mGET /mine?appid={{vault:openweather-api-api-key:value}} HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:17:05] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:17:34] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:17:35] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
ERROR:server:Exception on /mine [GET]
Traceback (most recent call last):
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\xampp\htdocs\basic_blockchain\server.py", line 22, in mine
    blockchain.new_transaction(
TypeError: Blockchain.new_transaction() missing 2 required positional arguments: 'private_key' and 'signature'
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:19:12] "[35m[1mGET /mine?appid={{vault:openweather-api-api-key:value}} HTTP/1.1[0m" 500 -
ERROR:server:Exception on /mine [GET]
Traceback (most recent call last):
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rizal\anaconda3\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\xampp\htdocs\basic_blockchain\server.py", line 22, in mine
    blockchain.new_transaction(
TypeError: Blockchain.new_transaction() missing 2 required positional arguments: 'private_key' and 'signature'
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:19:13] "[35m[1mGET /mine?appid={{vault:openweather-api-api-key:value}} HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 18:22:04] "[35m[1mPOST /transactions/new HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [26/Jul/2024 19:12:56] "[31m[1mPOST /transactions/new HTTP/1.1[0m" 400 -
